### ISSUE TITLE
The demo

### ISSUE THREAD

**Issue by limelect** [RynoCoetzee/TRCGPlaceAutoCompleteCombo#1]
The demo + Component suppose to do autocomplete
well, it does not.
One more thing on the demo the weel is turning on every 3 .
it suppose to be after 3 everyone.
Using D10.2.3

**Comment by RynoCoetzee** [comment]
Hi, could you be more descriptive in your report, does it give an error, 
did you assign your Google API key property?

Try capturing the OnAutoCompleteRESTRequestFailed and 
OnFillPlaceRESTRequestFailed and 
TRCGPlaceAutocompleteCombo.LastResponseStatus and report the error if 
any please

Also note that the component is compatible with 10.3.3 and above only as 
there has been issues with the TJson.JsonToObject RTL that was fixed in 
10.3.3 that I remember I had issues with in 10.x.x

**Comment by limelect** [comment]
You left your key. Using it.
I hop it works
With it, it does nothing

**Comment by RynoCoetzee** [comment]
Ah thanks for pointing that out, I'll have to disable that key though.. You'll need to visit https://developers.google.com/places/web-service/get-api-key to get your own

**Comment by limelect** [comment]
All 2 Breakp on fail one on memo nothing no fail no memo
